### PR TITLE
FIX : couldn't find CrownSegmentationcli.py

### PR DESCRIPTION
**Pull request by GaelleLeroux**
Hi @allemangD !

I had the same problems we have with ALI_IOS on Windows. I need the full path to the CrownSegmentationcli.py file to run it in wsl. I've created a function based on Slicer's PYTHONPATH to find the file. What do you think ? 
If you're ok, I'll do the same thing on ALI_IOS after this merge.

Thank you !
Gaelle

### CODE REVIEW

**Review by allemangD — COMMENTED** [review]
I would not use this directly. I only mentioned pythonpath because it informs the setup of import functionality; in certain cases it might miss paths, or include "fallback" paths you don't actually want.

The better way is instead to add the necessary directory to the pythonpath of the _conda_ environment, so that a plain import will work.

The module `CrownSegmentation.py` and `CrownSegmentation_utils/` must be somewhere in Slicer's module search paths.

You can find the active search paths with:

```py
slicer.app.moduleManager().factoryManager().searchPaths
```

This includes the `qt-loadable-modules`, `qt-scripted-modules`, `cli-modules`, and any other user-configured paths for from-source module installations.

Adding these to the conda environment path will ___not___ be able to `import slicer` from this path. But you will be able to `import CrownSegmentation_utils.install_pytorch` or launch `path/to/conda/python -m CrownSegmentation_utils.install_pytorch`.

---

I suggest making this change in SlicerConda, so that either by default or with a flag, the conda environment will include the slicer app search paths.

Conda has the `conda env config vars set` command, which sets environment variables for that conda environment.

For example a command like 

```sh
conda env config vars set -n $name PYTHONPATH=/path/to/cli-modules:/path/to/qt-loadable-modules:/path/to/qt-scripted-modules
```

However I _do not_ know if this will work on WSL. I think it should, but I've never tried it. You'd need to do the `windows_to_linux_path` transformation on each item so it takes the absolute path from `/mnt`.

I'd guess something like this would work:

```py
paths = slicer.app.moduleManager().factoryManager().searchPaths
mnt_paths = [windows_to_linux_path(path) for path in paths]
pythonpath_arg = 'PYTHONPATH=' + ':'.join(mnt_paths)
subprocess.run([conda_exe, 'env', 'config', 'vars', 'set', '-n', name, pythonpath_arg])
```

The `windows_to_linux_path` step would not be needed on linux/mac.

And then you'd be able to directly run the file:

```py
subprocess.run([conda_exe, 'run', '-n', name, 'python', '-m', 'CrownSegmentationCLI_utils.install_pytorch'])
```

or run a file with `import CrownSegmentationCLI_utils.install_pytorch`

**Comment by allemangD** [comment]
At a glance it looks like https://realpython.com/python-import/ has good information on the import system and search paths.

https://docs.python.org/3/reference/import.html is the reference documentation but it is difficult to read if you don't already understand it in detail. I suggest you review the realpython link.

The relevant section for this is [Python's Import Path](https://realpython.com/python-import/#pythons-import-path) - but that entire page has valuable information and demonstrations.

**Comment by GaelleLeroux** [comment]
Adding the PYTHONPATH to my environment in WSL seems to work. When I manually add FlexReg in Slicer and do the step you suggested, it works fine. But when I try to run requirement.py (located in ALI/ALI_IOS_utils in the DCBIA repository), I can't find it, even though I see the file on the computer after downloading AutomatedTools as a user. 

When I run a command in the python console of Slicer to get more details about the paths it knows that are linked to SlicerAutomatedDentalTools. I can see the path to ALI.py and some files in AREG_Method but I can't see any path with ALI_IOS_utils in it. I can't understand why it knows the path to Reader.py (located in ASO/ASO_Method_IOS_utils/ in the DCBIA repository) and not the requirement.py path. Do you have an explanation and how I can solve it ? 
image

Thank you !

**Comment by allemangD** [comment]
You'd access it from python via `import ALI_IOS_utils.requirement`, or you'd execute it via command line (assuming PYTHONPATH is set properly) with `-m` option like `conda run ... python -m ALI_IOS_utils.requirement`.

`sys.modules` contains only the modules that have already been loaded. If nothing has imported a module yet, it won't appear in sys.modules.

However if you inspect `sys.path` - or notice the location of modules like `ALI`, `AMASSS`, etc. - you'll see `..../qt-scripted-modules` on the path. That's the root that's searched for modules; when you `import` or `-m` `ALI_IOS_utils.requirement` python will look at `..../qt-scripted-modules/ALI_IOS_utils/requirement.py`.

**Comment by GaelleLeroux** [comment]
@allemangD 

I think I did it, it works fine on my computer! Can you tell me if it's good and if so merge it? 

Thank you !

**Pull request merged**
